version: '3.7'

services:
    react:
        container_name: react
        image: react
        restart: always
        build: 
            context: ./my-app
            dockerfile: ./my-app/Dockerfile
        ports:
            # - "8184:80" # for prod
            - "80:3000"